Finish the first task
roriwa/WebB5 pull request #2
Opened 2023-01-28 11:15 UTC by Niklas003

This PR should check all items that are on the list for the first task.

2023-01-28 12:25 UTC, JuliusJaenchen requested changes

2023-01-28 12:25 UTC, JuliusJaenchen commented on index.html
> +        <form>
Form brauchen wir nicht, das ist schon auf der submit-recipe.html Seite eingebaut.

2023-01-28 12:25 UTC, JuliusJaenchen commented on index.html
> +    <link rel="stylesheet" href="style.css">
kannst du das Stylesheet auch auf submit-recipe.html einbinden?

2023-01-28 12:25 UTC, JuliusJaenchen commented on index.html
> +                    <td>Third</td>
```suggestion
                    <td>Name</td>
                    <td>Number of Ingredients</td>
```
Könntest du das und dann die dazugehörigen Tabelen-Daten anpassen?

Das würde dann zu der submit-recipe.html Seite passen.

2023-01-28 14:07 UTC, Niklas003 commented on index.html
> +        <form>
Done

2023-01-28 14:07 UTC, Niklas003 commented on index.html
> +    <link rel="stylesheet" href="style.css">
Done

2023-01-28 14:07 UTC, Niklas003 commented on index.html
> +                    <td>Third</td>
Done

2023-01-29 13:56 UTC, JuliusJaenchen approved these changes

2023-01-29 14:18 UTC, roriwa approved these changes

2023-01-30 09:52 UTC, merged